### ISSUE TITLE
Сделай автоматическое заполнение капчи.

### ISSUE THREAD

**Issue by SpeakeazyYT** [xTCry/hsAutoClicker#2]
Здравствуйте. Есть идея и её решение. Можешь сделать автозаполнение капчи. Для этого используем сервис с их API - https://anti-captcha.com . Также вот примеры на GitHub по применению API на Node JS - https://github.com/AdminAnticaptcha/anticaptcha-nodejs (example_image.js). В методе anticaptcha.createImageToTextTask есть поле body, вот в нём принимаются только Base64 значения, но не ссылки. Для конвертирования ссылок в Base64 используй image2base64:

> const image2base64 = require('image-to-base64');
image2base64("https://api.vk.com/captcha.php?sid=405226711931&s=1") // you can also to use url
	.then(
		(response) => {
			console.log(response); //cGF0aC90by9maWxlLmpwZw==
		}
	)
	.catch(
		(error) => {
			console.log(error); //Exepection error....
		}
	)

**Comment by xTCry** [comment]
Да можно сервис подключить

**Comment by SpeakeazyYT** [comment]
xTCry, добавь меня в ВК - https://vk.com/anonymous535
У меня решение с антикапчей уже готово, хотел с тобой поделиться.

**Comment by Mimikatz** [comment]
Прикрути рукаптчу и возможность выставления задержки между сообщениями вручную (:

**Comment by xTCry** [comment]
Done.
