### ISSUE TITLE
Автоматический перевод на аккаунт 

### ISSUE THREAD

**Issue by nirikikry** [xTCry/hsAutoClicker#4]
Добавьте команду что бы переводились коины на аккаунт. Было бы очень удобно

**Comment by xTCry** [comment]
Эта команда есть - `drop`

**Comment by nirikikry** [comment]
Не правильно выразился. Я хотел бы что бы кликалась на одном аккаунте и переводил бы коина на другой автоматически

**Comment by quick-wq** [comment]
В курсе что это другой бот ВК? В нем эта функция не предусмотрена же.
Запускай тот скрипт и переводи.
