### ISSUE TITLE
Don`t work pc (planet clicker module)

### ISSUE THREAD

**Issue by httsmvkcom** [xTCry/hsAutoClicker#7]
![image](https://user-images.githubusercontent.com/51028674/58373054-25bfdf00-7f30-11e9-9cec-d85a2799a92c.png)
selmod planetclicker or HappySanta don`t work too 
Сори за май энглиш

**Comment by aeonixlegit** [comment]
PlanetClicker не работает, ибо 20 мая там было обновление полезной нагрузки в сообщениях, однако 'Бот Кликер’ должен работать.

**Comment by httsmvkcom** [comment]
Спасибо!
